require 'pry'

x = ["NO PARKING MIDNIGHT-6AM INCLUDING SUNDAY",
"NO PARKING SUNDAY & HOLIDAYS (SINGLE ARROW)",
"NO PARKING 1PM-MIDNIGHT SATURDAY (SINGLE ARROW)",
"NO PARKING ANYTIME MAY 15 - SEPT 30",
"NO PARKING 8AM-5PM MON THRU FRI",
"NO PARKING (SANITATION BROOM SYMBOL) 7:30-8:30AM EXCEPT SUN",
"NO PARKING ANYTIME EXCEPT TRUCKS",
"NO PARKING SAT SUN HOILDAYS MAY 15 - SEPT 30",
"NO PARKING 7-10AM 4-7PM MON THRU FRI",
"NO PARKING 8AM-6PM MON THRU FRI EXCEPT STATE OWNED VEHICLES",
"NO PARKING 7-9AM 4-7PM EXCEPT SUNDAY"]

y = x.first[/((?:EXCEPT\s)|(?:INCLUDING\s))?((?:MONDAY|\bMON\b)|(?:TUESDAY|\bTUE\b)|(?:WEDNESDAY|\bWED\b)|(?:THURSDAY|\bTHURS\b)|(?:FRIDAY|\bFRI\b)|(?:SATURDAY|\bSAT\b)|(?:SUNDAY|\bSUN\b)|(?:THRU))\s?((?:MONDAY|\bMON\b)|(?:TUESDAY|\bTUE\b)|(?:WEDNESDAY|\bWED\b)|(?:THURSDAY|\bTHURS\b)|(?:FRIDAY|\bFRI\b)|(?:SATURDAY|\bSAT\b)|(?:SUNDAY|\bSUN\b)|(?:THRU))?\s?((?:MONDAY|\bMON\b)|(?:TUESDAY|\bTUE\b)|(?:WEDNESDAY|\bWED\b)|(?:THURSDAY|\bTHURS\b)|(?:FRIDAY|\bFRI\b)|(?:SATURDAY|\bSAT\b)|(?:SUNDAY|\bSUN\b)|(?:THRU))?/]


hash = {
	:SUNDAY => nil ,
	:MONDAY => nil ,
	:TUESDAY => nil ,
	:WEDNESDAY => nil ,
	:THURSDAY => nil ,
	:FRIDAY => nil ,
	:SATURDAY => nil
}

hash.map do
	|k, v|
	k.each do
		v = times
	end
end



binding.pry


